# Generated by Django 3.2.5 on 2021-07-17 15:30

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
