# Generated by Django 3.2.5 on 2021-07-17 15:39

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_hospital_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
