# Generated by Django 3.2.5 on 2021-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_hospital_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
