# Generated by Django 3.2.5 on 2021-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210718_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30, null=True),
        ),
    ]
