# Generated by Django 3.2.5 on 2021-07-18 07:13

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210718_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
