# Generated by Django 3.2.5 on 2021-07-18 07:22

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210718_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condition_level',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
