# Generated by Django 3.2.5 on 2021-07-18 07:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_patientlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='bed',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='hospital', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bed'),
        ),
    ]
