# Generated by Django 3.2.5 on 2021-07-18 10:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_ambulance_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
