# Generated by Django 3.2.5 on 2021-07-18 17:14

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address2',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='geolocation2',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
