# Generated by Django 3.2.5 on 2021-07-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210719_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='geolocation2',
        ),
    ]
