# Generated by Django 3.2.5 on 2021-07-21 04:45

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='src',
        ),
        migrations.AddField(
            model_name='points',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
