# Generated by Django 3.2.5 on 2021-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210721_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
