# Generated by Django 3.2.5 on 2021-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210721_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
