# Generated by Django 3.2.5 on 2021-07-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_points_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.ambulanceticket'),
        ),
    ]
