# Generated by Django 3.2.5 on 2021-07-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20210725_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('request', 'Request'), ('process', 'Process'), ('complete', 'Complete')], max_length=30, null=True),
        ),
    ]
