# Generated by Django 3.2.5 on 2021-07-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postcat',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcat_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcat',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcat_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
