# Generated by Django 3.2.5 on 2021-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_product_postphoto_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
