# Generated by Django 3.2.7 on 2021-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_file', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Hospital (csv)')),
            ],
        ),
    ]
