# Generated by Django 3.2.7 on 2021-09-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_wellnessimportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessstore',
            name='sha15_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='wellnessstore',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wellnessimportfile',
            name='store_file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Store (csv)'),
        ),
    ]
