# Generated by Django 3.2.5 on 2021-07-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruit.producttype'),
        ),
    ]
