# Generated by Django 3.2.5 on 2021-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0007_auto_20210727_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
