# Generated by Django 3.2.5 on 2021-08-02 13:57

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0009_auto_20210802_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruit.producttype'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_cat',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fruit.storecat'),
        ),
    ]
