# Generated by Django 3.2.6 on 2021-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0011_auto_20210802_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
