# Generated by Django 3.2.6 on 2021-08-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0018_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('read', 'Read'), ('process', 'Process'), ('complete', 'Complete')], default='request', max_length=30),
        ),
    ]
