# Generated by Django 3.2.6 on 2021-08-09 07:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0021_vendororder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororder',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vendor', chained_model_field='vendor', null=True, on_delete=django.db.models.deletion.CASCADE, to='fruit.product'),
        ),
    ]
