# Generated by Django 3.2.6 on 2021-08-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0022_alter_vendororder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
