# Generated by Django 3.2.6 on 2021-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0023_alter_vendororder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='product',
        ),
        migrations.AddField(
            model_name='vendor',
            name='products',
            field=models.ManyToManyField(to='fruit.Product'),
        ),
    ]
