# Generated by Django 3.2.6 on 2021-08-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0026_remove_vendor_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fruit.product'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fruit.store'),
        ),
    ]
