# Generated by Django 3.2.6 on 2021-08-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0029_auto_20210815_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='seller', max_length=30),
        ),
    ]
